resources:
  - name: source
    type: git
params:
  - name: gitrevision
    type: string
  - name: gitrepositoryurl
    type: string
tasks:
  - name: say-hello
    taskSpec:
      steps:
        - name: ls
          image: ubuntu
          script: |
            #!/usr/bin/env bash
            echo "hello"