apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: sample-
spec:
  pipelineSpec:
    tasks:
      - name: hello-commit
        taskSpec:
          steps:
            - name: hello
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo $GIT_REVISION
